services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_NAME=mydatabase
      - ELASTIC_APM_SERVER_URL=https://YOUR_CLUSTER_ID.apm.REGION.cloud.es.io:443
      - ELASTIC_APM_SERVICE_NAME=my-service-haruto
      - ELASTIC_APM_SECRET_TOKEN=YOUR_SECRET_TOKEN_HERE
      - ELASTIC_APM_ENVIRONMENT=my-environment

volumes:
  mysql_data:
