services:
  elasticsearch-apm:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.1
    container_name: es-node-8.17.1-apm
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - ELASTIC_PASSWORD=changeme
      - xpack.security.enabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata-8140-apm:/usr/share/elasticsearch/data
    ports:
      - 9201:9200  # Changed port mapping to avoid conflict
    networks:
      - elastic-apm

  kibana-apm:
    image: docker.elastic.co/kibana/kibana:8.17.1
    container_name: kibana-node-8.17.1-apm
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch-apm:9200
      - ELASTICSEARCH_SERVICE_TOKEN=YOUR_SERVICE_ACCOUNT_TOKEN
      - xpack.security.enabled=true
    ports:
      - 5608:5601
    networks:
      - elastic-apm
    depends_on:
      - elasticsearch-apm
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  apm-server:
    image: docker.elastic.co/apm/apm-server:8.17.1
    container_name: apm-server-apm
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch-apm:9200
      - KIBANA_HOST=http://kibana-apm:5601
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=changeme
      - apm-server.secret_token=your_secret_token
      - xpack.security.enabled=true
    ports:
      - "8200:8200"
    networks:
      - elastic-apm
    depends_on:
      - elasticsearch-apm
      - kibana-apm

volumes:
  esdata-8140-apm:
    driver: local

networks:
  elastic-apm:
    driver: bridge