input {
  elasticsearch {
    hosts => "https://c9c767b07f2540b29168b7d0e0377c92.asia-northeast1.gcp.cloud.es.io"

    user => "elastic"
    password => "q5brmxu5VdrjBfYi78qj6RkF"
    index => ".ds-elastic-cloud-logs-*"
      query => '{
        "query": {
          "bool": {
            "must": [],
            "filter": [
              {
                "range": {
                  "@timestamp": {
                    "gte": "now-10m",
                    "lt": "now-5m",
                    "time_zone": "+09:00"
                  }
                }
              },
              {
                "bool": {
                  "minimum_should_match": 1,
                  "should": [
                    {
                      "match_phrase": {
                        "event.dataset": "elasticsearch.audit"
                      }
                    },
                    {
                      "match_phrase": {
                        "event.dataset": "kibana.audit"
                      }
                    }
                  ]
                }
              }
            ],
            "should": [],
            "must_not": []
          }
        }
}'
    size => 2000
    scroll => "5m"
    schedule => "*/1 * * * *"
  }
}

output {

  stdout { 
    codec => rubydebug 
  }
}

